### ISSUE TITLE
HTTP01 support tracking issue

### ISSUE THREAD

**Issue by ohemorange** [certbot/certbot#5409]
General things to remember/ edge cases/ considerations go here.

~Apache issue: #5410~
~Nginx issue: #5411~
~Nginx follow-up PR: #5409~

- [x] Update `certbot.eff.org` to show a short message about what's going on with useful links.
- [x] Try and properly handle redirects and proxying for HTTP01 in Apache. Failing that, include logging about the error.
- [x] Ensure HTTP01 challenge succeeds in nginx when the server is not currently listening on the HTTP01 port. (#5421)
- [x] Serve 404s from dummy nginx block ~or convince ourselves it will never serve sensitive content~. (#5437)
- [x] Write nginx unit/system tests.
- [x] Add a rewrite directive for the .well-known location so we don't hit existing rewrites (#5436)

**Comment by ohemorange** [comment]
@bmw's main concerns:

1) Redirects, proxypass directives, etc. taking precedence
2) Making sure Apache/Nginx is happy to serve files out of that directory and doesn't complain about permissions

**Comment by bmw** [comment]
To expand slightly:

1. We should make sure the HTTP-01 response is served regardless of any redirects, proxying, etc. the user may have configured for that domain.
2. Apache (and I think Nginx) allow you to set permissions for different paths on where the server can and cannot serve files from. We should make sure this doesn't stop the challenge from being served.
3. Nginx (and maybe Apache) sometimes don't like serving files from hidden directories. We should make this doesn't break the challenge.
4. In `get_chall_pref`, we should return TLS-SNI before HTTP. HTTP will be used if TLS-SNI isn't available, but TLS-SNI has been tested WAY more in these plugins so we should probably use TLS-SNI if the server supports both.

**Comment by ohemorange** [comment]
Is TLS-SNI off in a way that will have us automatically fall through to HTTP?

**Comment by bmw** [comment]
Yep. You can test that with standalone if you want. It's set up the way I describe in 4.

5. For the HTTP challenge, the CA will always request the file over plain HTTP rather than HTTPS. We should try to do the right thing when the vhost we're doing the challenge for is either HTTP or HTTPS.

**Comment by ohemorange** [comment]
HTTP is only available over HTTP, not HTTPS.

**Comment by bmw** [comment]
For certbot.eff.org we want, a short note on certbot.eff.org with links to what's going on. You may want to link to some combination of:

* https://community.letsencrypt.org/t/help-test-certbot-apache-and-nginx-fixes-for-tls-sni-01-outage/50207
* https://community.letsencrypt.org/t/solution-client-with-the-currently-selected-authenticator-does-not-support-any-combination-of-challenges-that-will-satisfy-the-ca/49983
* https://community.letsencrypt.org/t/2018-01-09-issue-with-tls-sni-01-and-shared-hosting-infrastructure/49996/

**Comment by bmw** [comment]
After spending multiple days trying to figure out how we can handle HTTP-01 in Apache, I've come up with a few options. Unfortunately, all of the options have side effects that aren't ideal and/or it won't work in all cases. It turns out that Apache configuration files are complicated. These options are roughly in the order I prefer them from most to least preferred.

### Option 1: Disable problematic directives

The way this would work is when setting up the challenge, we look at the enabled modules to see what could cause us to not successfully complete the challenge. If there are modules that we know can override the behavior we want, we try to disable their functionality when handling the challenge file. This would look something like:
```
<Location /.well-known/acme-challenge>
ProxyRequests off
ProxyPass !
RewriteEngine off
</Location>
```
If we go with this approach, I think we should (at least) do this at the top level of the Apache configuration (in `/etc/apache2/apache2.conf` or a file it includes).

Pros are:
* Simple to implement
* It affects all virtual hosts so if we're unable to disable something like a mod_alias `Redirect` directive and it just redirects to www or HTTP->HTTPS or any content on the same server, we'll still properly serve the file.

Cons of this approach are:
* We cannot handle mod_alias `Redirect`s that cause a redirect to a domain that is handled somewhere other than the Apache instance we're modifying.
* There may be problematic directives we're missing.
* If we only do this at the top level of the Apache config and the user has a `Location` directive in their virtual host that contains a prefix of `/.well-known/acme-challenge`, settings they put in it while override our settings. I think this is fairly unlikely, but we could work around this if we wanted by putting our `Location` directive at the bottom of the challenge virtualhost in addition to doing it at the top level.

If we go with this approach, problematic directives we may want to consider are:
* SetHandler
* RewriteEngine
* ProxyPass
* ProxyRequests
* OutputFilter

### Option 2: HTTP-01 takes your normal site offline

This one is pretty straightforward. If there is a matching vhost for your domain, we remove it while we serve the challenge and replace it when the challenge is finished. Your normal site becomes unavailable over HTTP during the challenge. The pros and cons of this are pretty straightforward. We can do things like ask the user if this is OK in interactive mode if we wanted.

### Other options

I had a couple more options. One involves making the normal vhost for the domain one that serves the challenge and acts as a reverse proxy to the normal vhost through a dummy domain name and localhost for all other traffic. The other involves posting the challenge contents to an external server and having Certbot configure a redirect to it. As you can imagine, both of these ideas have their problems, but let me know if you'd like to see my notes on them.

**Comment by bmw** [comment]
### Option 3: We proxy normal web traffic

We take the vhost that normally serves HTTP content for the domain (if it exists), remove any matching `ServerName` and `ServerAlias` directives, and add a new `ServerName`/`ServerAlias` for an invalid domain name like `certbot.invalid`.

Finally, we set up a new vhost for the challenge domain(s) with content like:
```
<VirtualHost *:80>
    ServerName example.com
    Alias /.well-known/acme-challenge /tmp/foo
    ProxyPass "/.well-known/acme-challenge" !
    ProxyPass "/" "http://localhost/"
    RequestHeader set Host certbot.invalid
    ProxyPreserveHost On
</VirtualHost>
```
The way this works is if the request is for the challenge file, we serve it, otherwise, we proxy the traffic back to Apache but change the host header to a dummy value which causes it to be handled by the original vhost which we modified. If there are multiple domains requested and they are in different virtualhost blocks, we'll need a different dummy domain name for each block and and separate challenge vhost.

Pros of this approach:
* I am unaware of a way this can stop us from serving the challenge.

Cons of this approach:
* While probably fairly unlikely, firewall rules may prevent us from proxying the traffic back to ourselves.
* If the site normally relies on the `Host` header for more than just vhost matching, setting it back to its correct value so it doesn't break anything may be hard.
* We may need/want to do extra work to make sure there are no extra headers modified by `mod_proxy` if possible.
* We need `mod_headers`, `mod_proxy`, and `mod_proxy_http` to be installed and enabled/enableable. This is the case on all the distros I've looked at, but still.
* We should make sure we properly implement `--http-01-address` (in theory we should do this anyway) in case Apache isn't listening on localhost.

### Option 4: Redirect to service hosting challenge files

We have our Apache plugin upload the contents of the file it should serve for the challenge to an external server and include something like this:
```
<Location /.well-known/acme-challenge>
    Redirect https://http01.certbot.eff.org/toiu41ht9814gjn2o
</Location>
```

The pros of this approach are:
* I have yet to see an Apache directive that breaks this approach.

Unfortunately, that's the end of the pros. The cons are:

* If this external service goes down, people cannot obtain certificates.
* If we're starting our own service, we have to maintain it.
* If we're not starting our own service, we need to be worried about things like API changes and reliability.
* This external service will be able to tell that someone is running Certbot Apache at the IP that uploads the challenge contents.
* People behind something like the great firewall may be unable to reach the service we use.

**Comment by jsha** [comment]
I think you mentioned in person that you'd ruled this out, but I can't remember why:

### Option 5: Add a `ProxyPass /.well-known/acme-challenge/` directive pointing to a `standalone` server running on a special port

[According to docs](https://httpd.apache.org/docs/trunk/en/mod/mod_proxy.html#proxypass):

> Ordering ProxyPass Directives
> The configured ProxyPass and ProxyPassMatch rules are checked in the order of configuration. The first rule that matches wins. So usually you should sort conflicting ProxyPass rules starting with the longest URLs first. Otherwise, later rules for longer URLS will be hidden by any earlier rule which uses a leading substring of the URL. Note that there is some relation with worker sharing. In contrast, only one ProxyPass directive can be placed in a Location block, and the most specific location will take precedence.

This could be combined with a no-op RewriteRule for `/.well-known/acme-challenge` at the highest-level part of the config, [using the L flag](https://httpd.apache.org/docs/2.4/rewrite/flags.html#flag_l) to terminate processing by mod_rewrite.

**Comment by bmw** [comment]
That's certainly a valid approach. My biggest concern is @pde looked into this a bit and found people having issues with firewalls even if we're just going through localhost. The hope was that with option 3 we'll be reusing the port already being listened to by Apache, but it's certainly more complex and has some of the same problems.

**Comment by joohoi** [comment]
Unix sockets would probably could have been an answer to that, but apparently they were introduced in 2.4.7 :(

**Comment by pde** [comment]
@jsha @bmw I don't think those issues are common. They're typically due to "personal firewall" software, probably not on Linux or other typical Certbot platforms, and probably not on servers.

Since we haven't found any other options (Other that `Alias` inside `Location`, which only works in recent Apache 2.4 releases) I do think we should seriously consider that `ProxyPass` option. As far as we know, it will work in all cases.

Some reasons I was nervous about it:
* it's more complicated than a pure Apache change
* we'd need to tweak the standalone plugin to make sure it listens only on localhost for this use (or on a UNIX domain socket?)
* we'd need to find a reliably free port
* we'd need to make sure we never have the problem of ports being unavailable for 30 seconds after they're closed

To be clear I think all of this is totally solvable, but might be a source of bugs or complexity if we do this in a hurry.

**Comment by pde** [comment]
Perhaps if we see any of the "localhost firewall" problems in the field we could use UNIX sockets for Apache > 2.4.7 and localhost TCP otherwise.

**Comment by pde** [comment]
I currently think the number 5 `ProxyPass` option is ugly but might be the best of the options that work in every case we know about?

**Comment by jsha** [comment]
> we'd need to tweak the standalone plugin to make sure it listens only on localhost for this use (or on a UNIX domain socket?)

Why is this necessar?

> we'd need to find a reliably free port

We could introduce an internal option for standalone to listen on "0", effectively saying "assign me a port." We'd then use the assigned port when inserting the ProxyPass directive.

> we'd need to make sure we never have the problem of ports being unavailable for 30 seconds after they're closed

If we ask to be assigned a port, this is not an issue.

**Comment by pde** [comment]
> Why is this necessary?
I don't mean that it's necessary for the plugin to only listen on localhost, but that we really need to ensure it's listening on localhost, which may no't been the case for that plugin previously.

Your port 0 suggestion may be enough to avoid any headaches in practice. The last question would be, how elegant / ugly will it be to invoke one authenticator from within another?

@bmw @joohoi thoughts? Should we start mocking up an implementation?

**Comment by jsha** [comment]
We also don't necessarily need to invoke the actual standalone authenticator. Setting up an HTTP server is simple enough that we could just have a separate one for use inside the Apache plugin. This would also mitigate the issue of needing internal plumbing for "port 0" and "what's your port?"

**Comment by joohoi** [comment]
IIRC @bmw faced some inconsistency in getting an open port allocated when binding to port 0 previously.

**Comment by jsha** [comment]
Also, we should consider: Are we concerned some installs might not have mod_proxy, or might have it disabled? If so, we'd need a fallback approach for those, which might make Option 5 less appealing.

**Comment by pde** [comment]
@jsha we have module enabling code which is fairly battle-tested. But if any OSes have packaged it separately, we'd need to add a new OS dependency. @joohoi can you think of corner cases where that might not be true? Eg platforms where the apache plugin can't find `a2enmod` or equivalent, but the user fixed it by hand?

If we need a fallback, we have the thing we've already implemented, though that still doesn't cover some redirect/rewrite cases.

**Comment by joohoi** [comment]
There's a lot of systems that we can't reliably enable modules on. While basically just symlinking where they do, `a2enmod` and `a2dismod` unfortunately exist in minority of the distributions.

Some distributions just basically deploy commented out module configurations for user to uncomment when needed, and some have their own imaginative ways of handling the same thing. OpenSUSE for example has a list in environmental variable form in its own configuration file that gets compiled to Apache configuration whenever Apache init scripts are called.

**Comment by jsha** [comment]
Thinking about this some more, I'm starting to think that Option 5 is just a less-good version of Option 1. The docs have two ways to grab the highest-precedence ProxyPass:

a> The configured ProxyPass and ProxyPassMatch rules are checked in the order of configuration. The first rule that matches wins.

b> In contrast, only one ProxyPass directive can be placed in a Location block, and the most specific location will take precedence.

In other words, you can be the first ProxyPass (a), or be a ProxyPass inside the most specific Location block (b). Option 1 chooses to be a ProxyPass inside the most specific Location block, and simply turns off ProxyPass and RewriteEngine. That should be at least as good as Option 5.

It may also be possible to use an even more specific Location block, like `Location /.well-known/acme-challenge/acb1358gjkdsfdsf`, and have a directive to return a certain literal string. I know this is [possible for ErrorDocuments](https://httpd.apache.org/docs/2.4/custom-error.html). I don't know if it's possible for non-errors. But this would save some mucking about with the filesystem.

**Comment by pde** [comment]
@jsha the huge advantage of Option 5 over Option 1 is that it's compatible with `mod_alias` Redirects to other servers.

But I agree we're finding some evidence that Option 1 might be easier to deploy.

**Comment by bmw** [comment]
> @jsha the huge advantage of Option 5 over Option 1 is that it's compatible with mod_alias Redirects to other servers.

But it's not. Based on my testing, even if you have the proxy set up, the `Redirect` will be served.

**Comment by pde** [comment]
@bmw bleh that's horrible

**Comment by bmw** [comment]
I think all checklist items needed for the release have been completed (with minor work on #5441 ongoing). I'm closing this PR and keeping it in the milestone.
