### ISSUE TITLE
TLSSNI removal TODO list

### ISSUE THREAD

**Issue by bmw** [certbot/certbot#5422]
This is a bit of an awkward issue but to post this somewhere trackable:

- [ ] Update `certbot.eff.org` to show a short message about what's going on with useful links.
- [ ] Try and properly handle redirects and proxying for HTTP01 in Apache. Failing that, include logging about the error.
- [ ] Ensure HTTP01 challenge succeeds in nginx when the server is not currently listening on the HTTP01 port.

**Comment by bmw** [comment]
Closing in favor of #5409.
