### ISSUE TITLE
Follow-ups from enabling HTTP-01

### ISSUE THREAD

**Issue by ohemorange** [certbot/certbot#5438]
Things we noticed need fixing while we were there (#5409), and code that can be cleaned up.

- `certbot-nginx/certbot_nginx/tls_sni_01.py` and `certbot-nginx/certbot_nginx/http_01.py` could use some deduping -- fix this when we need to
- (nginx) tls sni should have `root` not inside a `location /` block -- probably not worth fixing
- [x] (#5787) (nginx) location is useless as a repeatable directive -- our repeatable directive infrastructure doesn't support blocks as the first argument
- [x] (#5794) code could use deduping internally to `certbot-nginx/certbot_nginx/http_01.py` -- for example, `rewrite_directive` is defined identically twice
- [x] (#5788) Nginx default checking: allow prefix matching of `default_server`, check by port more often, use the first block found listening on that port like Nginx does, be IPv6 sensitive
- [x] (#5793) When copying a default block, remove ipv6only=on because this completely breaks it haha
- "While reviewing, I thought of a few things that are a corner cases of corner cases so it's probably not worth investing much (or maybe any) engineering effort in, but I think in theory we could do better with the address we use on the listen statement in some cases, mainly when creating our own dummy server block.

One case is Certbot takes an --http-01-address flag that matches the port flag. If someone set this, we should ideally respect it and when creating a dummy server block, we should have nginx use that address rather than listening on all interfaces. It's worth noting I didn't do this right in Apache either.

The second case is what if someone sets this and we find an existing server block to use. In theory, I think the behavior would be to use the server block only if it's listening on the same address, but this would likely get complicated when trying to compare the different variations of "listen on all interfaces".

The final case is [now located at #5795].

I think it's probably worth resolving the --http-01-address case for the dummy server block. Not so sure about the other cases." -- add this if anyone ever requests or complains about it
