### ISSUE TITLE
DNS plugins wildcards tracking issue

### ISSUE THREAD

**Issue by ohemorange** [certbot/certbot#5667]
Can we issue for wildcard and base domain simultaneously?

- [x] certbot-dns-cloudflare
- [ ] certbot-dns-cloudxns
- [x] certbot-dns-digitalocean
- [ ] certbot-dns-dnsimple (known issue)
- [ ] certbot-dns-dnsmadeeasy
- [x] certbot-dns-google
- [ ] certbot-dns-luadns
- [ ] certbot-dns-nsone
- [x] certbot-dns-rfc2136
- [x] certbot-dns-route53

**Comment by bmw** [comment]
While this was useful for us while actively working on it, I'm closing in favor of #5472 which has more context.
