### ISSUE TITLE
Certbot Windows installer feature tracker

### ISSUE THREAD

**Issue by bmw** [certbot/certbot#7365]
This issue is just to help us track the various features we want to look into for our Windows installer. This list started at https://github.com/certbot/certbot/pull/7324#issue-307052277 which I modified a bit:

- [x] register a scheduled task for certificate renewal
- [ ] auto-update of Certbot when a new release is available
- [x] online documentation for Windows
- [ ] installer distribution plan (continuous deployment + distribution channels)
- [ ] method to check the downloaded installer is untampered
- [x] pin runtime dependencies
- [x] pin build dependencies
- [ ] installation of additional plugins, such as 3rd party plugins
- [ ] Make our installer trusted by Windows

EDIT: Making our installer trusted by Windows is a thing I think we should look into that was flagged by Adrien.

**Comment by bmw** [comment]
I think this is the list of features we need before fully claiming to support Certbot on Windows, but we could offer a beta before a lot of these features are resolved.

**Comment by adferrand** [comment]
In order to meet two more requirements: check that the downloaded installer is untampered + make our installer trusted by Windows.

The solution is Microsoft Authenticode. This is a Windows built-in functionality that is able to check that a file (including executables) is genuine: it allows to authenticate its source and that its content is not tampered.

Without this, any execution of the installer would generate a warning that the user will need to explicitly override to continue installation. And of course an error would be thrown if the installer has been modified in any way.

Microsoft Authenticode is implemented on top of X509 certificates functionalities: content is signed and associated to a certificate, and a chain of trust is used to validate the certificate against CA root certificates accepted by the system. At this point, something like the bells of Notre-Dame should have rung to the reader.

Here is a working example to generate a code-signing certificate from an arbitrary CA, and to use it to sign the Certbot for Windows installer. Compatible with Linux :)

```bash
#!/bin/bash

# Requirements:
#  - OpenSSL is installed
#  - Mono is installed (it includes the signcode binary)
#  - CA key (myCA.key) and cert (myCA.pem) files are available locally
#  - Certbot for Windows installer file is available locally

# Prepare OpenSSL configuration for CSR
cat << EOF > openssl.cfg
[req]
req_extensions = v3_req
distinguished_name = req_distinguished_name
prompt = no

[req_distinguished_name]
C = US
ST = CA
L = San Francisco
O = EFF
OU = Certbot dev team
CN = Electronic Frontier Foundation

[v3_req] 
basicConstraints = CA:FALSE
keyUsage = digitalSignature
extendedKeyUsage = codeSigning
EOF

# Prepare OpenSSL configuation for CSR signing
cat << EOF > code-signing.cfg
subjectKeyIdentifier=hash
keyUsage = digitalSignature
extendedKeyUsage = codeSigning
EOF

# Generate the CSR
openssl req -new -key eff.key -out eff.csr -config openssl.cfg
# Sign the CSR for code signing usage
openssl x509 -req -days 3650 -in eff.csr -CA myCA.pem -CAkey myCA.key -extfile code-signing.cfg -out eff.crt -sha256

# Export key to PVK format
openssl rsa -in eff.key -outform PVK -pvk-none -out eff.pvk
# Export cert to SPL format
openssl crl2pkcs7 -nocrl -certfile eff.crt -outform DER -out eff.spc

# Sign the installer with the PVK+SPL files
/path/to/signcode -spc eff.spc -v eff.pvk -a sha256 -n "Certbot for Windows (beta)" \
    -t http://timestamp.verisign.com/scripts/timstamp.dll -tr 20 /path/to/certbot-beta-installer-win32.exe
```

I confirm here that if the CA root certificate is part of the Windows trusted store of the local machine, the installer is properly accepted by Microsoft Authenticode.

**Comment by bmw** [comment]
Awesome!

If this turns into a lengthy discussion we should probably move it elsewhere, but am I correct that Microsoft Authenticode just checks that the executable is signed by a key contained in a certificate that is trusted by Microsoft? If so, for our own purposes of verifying new versions of the executable we download, I think we should probably rely on the executable being signed with a specific key. The benefit of this is we can be sure the executable we downloaded and are about to run came from us rather than any source trusted by Microsoft.

I don't think this will be hard to implement. In certbot-auto, downloading and verifying new versions is just a few lines of code: https://github.com/certbot/certbot/blob/f555e4bf1ff33c11008f39d413b7d03f75b3fc0b/letsencrypt-auto-source/pieces/fetch.py#L95-L120

**Comment by adferrand** [comment]
To be more precise, Authenticode is about ensuring authenticity and integrity. The executable content itself is signed with a key. So first Windows can verify that the signature is genuine, using a certificat chain trust very similar to TLS, and it can also verify that the content is not tampered using this signature. So yes, it is totally doable to verify that the signature used a precise key, and refuse to execute the downloaded installer otherwise.

I will add this when I will implement auto update, and when we have the code signing certificate.

**Comment by mikenor** [comment]
May I suggest an addition to the list here?
- [ ] create Windows Firewall rule for `%ProgramFiles(x86)%\Certbot\Python\python.exe` (necessary for `--standalone` to work)

**Comment by bmw** [comment]
For "installer distribution plan (continuous deployment + distribution channels)", I think we have a few options:

1. Do a bit of threat modeling and convince ourselves we're fine giving Azure the permissions it needs to create GitHub releases.
2. [If Azure makes the change in a week and a half to allow Azure to create GitHub releases with its existing permissions](https://github.com/microsoft/azure-pipelines-tasks/issues/9754#issuecomment-626352963), do that. If it needs new permissions, see 1.
3. Write a script we run locally that pulls the files from Azure and publishes them to GitHub.

My personal preference between these options from most to least preferred are: 2, 1, 3

**Comment by bmw** [comment]
I think there's value in being a bit more specific in what we're tracking here so I just created #8046, #8047, #8048, #8049, and #8050 which I believe covers everything here.

If anyone things I missed something, please let me know or create a new issue.
