### ISSUE TITLE
Tracking issue for this set of "terminal revamp" PRs

### ISSUE THREAD

**Issue by alexzorin** [certbot/certbot#8560]
The "final" set of PRs for this cycle of the terminal revamp need to be reviewed and merged in one release, because merging them separately isn't viable.

This issue tracks their individual submission and approval. 

Once each is approved individually, then we can do a final review and merge.

- [x] #8318: nginx,apache: CLI logging changes
- [x] #8513: cli: redesign output of new certificate reporting
- [x] #8514: cli: redesign output of failed authz reporting
- [x] #8579: cli: dont use IReporter for EFF donation prompt
- [x] #8636: cli: redesign output when cert installation failed
- [x] #8622: renew: don't restart the installer for dry-runs
- [x] #8664: log: print "advice" when exiting with an error
- [x] #8765: cli: reduce default logging verbosity #2
