### ISSUE TITLE
ECDSA-by-default tracking issue

### ISSUE THREAD

**Issue by alexzorin** [certbot/certbot#9185]
Before 2.0:

- [x] certonly/run: Change the unexpected key migration prompt to be interactive and change the default non-interactive behavior to preserve the key type and key parameters. (https://github.com/certbot/certbot/pull/9200)
- [x] certonly/run: Always store key type in renewal parameters. (#9217)
- [x] Warn about the upcoming ECDSA by default change through channels like the community forum, mailing list, and the changelog (https://github.com/certbot/certbot/issues/9263)
- [x] certonly/run/renew: Add `--new-key` flag as first part of resolving [`--reuse-key` ambiguity](#7711) (https://github.com/certbot/certbot/pull/9252)

In 2.0 release:

- [x] certonly/run/renew: Fully resolve #7711 by erroring out on ambiguous flags (https://github.com/certbot/certbot/pull/9262)
- [x] Change default `key_type` to `ecdsa` (#9353)

**Comment by bmw** [comment]
I edited your post making a couple minor tweaks, but this list largely looks good to me. In particular, good job in noting the following which I don't think had been done explicitly before:

>  certonly/run: Always store key type in renewal parameters.

I have a question about this item though:

>  renew: preserve existing key type and key parameters unless overridden by CLI

What change needs to be made here?

**Comment by alexzorin** [comment]
>What change needs to be made here?

I think my concern here was part of the changes we're going to make to `reuse_key`. Since the previous item now mentions `renew` explicitly, we can roll it into that.

**Comment by bmw** [comment]
Ah OK. I've made that edit to your original post.

**Comment by alexzorin** [comment]
I don't think there's any work remaining for ECDSA-by-default.
